on:
  repository_dispatch:
  push:
    branches: master

name: Render & Deploy Site

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: typst-community/setup-typst@v4
      - uses: astral-sh/setup-uv@v7
      - run: uv run build.py build -f
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: _site

      - name: Download CV and commit to gh-pages
        run: |
          git fetch origin gh-pages || true
          git checkout gh-pages || git checkout --orphan gh-pages
          curl -L -o cv.pdf https://raw.githubusercontent.com/etiennebacher/CV_perso/master/cv.pdf
          git add cv.pdf
          git commit -m 'Update CV' || echo "No changes to commit"
          git push origin gh-pages || echo "No changes to commit"
