on:
  repository_dispatch:

name: Update CV

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Download CV and commit
        run: |
          curl -L -o content/cv.pdf https://raw.githubusercontent.com/etiennebacher/CV_perso/master/cv.pdf
          cp content/cv.pdf _site/cv.pdf
          git add _site/cv.pdf content/cv.pdf
          git commit -m 'Update CV' || echo "No changes to commit"
          git push
