on:
  repository_dispatch:
  push:
    branches: [main, master]

name: Render & Deploy Site

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Download CV and commit
        run: |
          curl -L -o cv.pdf https://raw.githubusercontent.com/etiennebacher/CV_perso/master/cv.pdf
          git add cv.pdf
          git commit -m 'Update CV' || echo "No changes to commit"
          git push
